### ISSUE TITLE
some players info page not load properly

### ISSUE THREAD

**Issue by aliemre2023** [El-Primos/blg317#31]
For player_id=3, Grant Long's data is not loaded, should fix.

<img width="500" alt="Screen Shot 2024-12-06 at 01 28 05" src="https://github.com/user-attachments/assets/168df990-6420-4dfe-b1ae-9cd83d4ce38c">

**Comment by kemaltahirbicilioglu** [comment]
null values were the reason. I fixed that

**Comment by SchumacherFarad** [comment]
thanks to @kemaltahirbicilioglu the issue is fixed.
