### ISSUE TITLE
bug when scrolling teams page

### ISSUE THREAD

**Issue by kemaltahirbicilioglu** [El-Primos/blg317#34]
When the team page is scrolled there is a little bug that we cannot see the very bottom of the team list.

**Comment by kemaltahirbicilioglu** [comment]
same thing happens for all the pages with the pagination

**Comment by aliemre2023** [comment]
> same thing happens for all the pages with the pagination

<img width="1238" alt="Screen Shot 2024-12-08 at 11 24 46" src="https://github.com/user-attachments/assets/00368e38-53c8-474c-8e66-52e48d332537">
in my local, other pages work properly I guess

**Comment by SchumacherFarad** [comment]
#66 is the PR to solve this issue. We can close this issue after merge.
