### ISSUE TITLE
Change suggestions for Color Codes

### ISSUE THREAD

**Issue by SchumacherFarad** [El-Primos/blg317#48]
I think we all want to change our color palette to something else so write here the color palettes you find and think that would fit our project.

**Comment by aliemre2023** [comment]
some useful sites
https://colorhunt.co/
https://color.adobe.com/tr/create/image
<img width="532" alt="Screen Shot 2024-12-08 at 22 20 33" src="https://github.com/user-attachments/assets/e92a1d25-c59f-439c-8443-8809bd88950d">

**Comment by SchumacherFarad** [comment]
#17408B
#FFFFFF
#C9082A

NBA's logo color schema. I think we can apply the red and blue both on dark and light themes on home page.

**Comment by SchumacherFarad** [comment]
https://nbacolors.com/
Then we can use this site and push the values to our teams table. Then for every Team Info page, we can change the color of the header and some divs in that pages

**Comment by SchumacherFarad** [comment]
As team colors are not any better than current visual, It's not an issue any more.
