### ISSUE TITLE
Primary Keys Should Be Auto-Incremented

### ISSUE THREAD

**Issue by umut373** [El-Primos/blg317#74]
Currently, the primary keys in some tables are not set to auto-increment. This can cause issues when adding new records, as the database does not automatically assign unique IDs. To ensure proper functionality and data integrity, all primary keys should be configured to auto-increment. Both table creation and validation scripts need to be updated.

**Comment by aliemre2023** [comment]
I added autoincrmeent for country table. but there is also  non autoincrement id tables (games, game_stats, players, player_infos) but those id's comes from original data already. So I suggest lets leave those same but when add a new player :
**'SELECT MAX(player_id) FROM players' + 1 (new_id)**
run that query, and fix the autoincrement issue

**Comment by aliemre2023** [comment]
nevermind, changing to autoincrement was easyier, thanks to you bro
